[package]
name = "rust_kvs"
version = "0.1.0"
authors = ["Ryo Kanbayashi <ryo.contact@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
